# Generated by Django 4.1.5 on 2023-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='bio', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='image'),
            preserve_default=False,
        ),
    ]
