# Generated by Django 4.1.5 on 2023-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal',
            new_name='desks',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.TextField(default='time'),
            preserve_default=False,
        ),
    ]
