# Generated by Django 4.1.5 on 2023-01-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_goal_project_desks_project_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
